name: Seatec
favicon: null
layout_spectrum: 0.21911
typography_spectrum: 0.07501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee0df'
    - '#050507'
    - '#607089'
    - '#88b9e1'
    - '#f2910c'
  brandStrength: 0.1875
  lightness: 0.7977090566419065
  saturation: 0.25
  rhythmicContrast: 0.4186744731850922
purpose: []
