name: Seatec
favicon: null
layout_spectrum: 0.04303124803118408
typography_spectrum: 0.47847803914919496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09153809072449803
  lightness: 0.7977090566419065
  saturation: 0.37888755835592747
  rhythmicContrast: 0.4186744731850922
purpose: []
